class Foo(arg)

async fn main() {
    let x = Foo(10, 22)
    #!      ^^^^^^^^^^^ RUN ERROR expected to find 1 arguments, but found 2
}